### ISSUE TITLE
向作者反馈几个问题

### ISSUE THREAD

**Issue by magic0908** [loperSeven/TitleBar#1]
首先非常感谢作者开源这个库，我最近整打算重新整理下标题栏这块，然后这个库让我眼前一亮，值得学习一番。
提两个demo的小问题：1、你把selector_btn_accent.xml放在了drawable-v24目录下，我运行的时候会报错，说是找不到这个drawable文件，然后我复制一份放在drawable目录下就可以了（手机是小米4W6.0系统）；2、点击菜单按钮跳转到浏览器的时候，要加intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);这句，不然有些手机会崩掉，有些就不会，这个有点坑。
还有一点就是，标题栏右边，可能是显示图标，可能是显示文字，你在代码里是通过setVisibility来控制显示与否的。有没有这样一种办法，就是我在需要的时候才会加载对应的控件，比如这个页面我只要显示图标，就只加载图标的控件，其他的不加载。不然一个标题栏却放置这么多控件，感觉还是挺沉重的。

**Comment by loper7** [comment]
谢谢你提出建议，不好意思了demo中犯了这种低级错误，titleBar总共放置了四个控件，返回（ImageView）、标题（TextView）、菜单（TextView）、下划线（View）  你说的需要显示才加载很有道理，找时间看看怎么优化一下，遇到其他问题请不吝赐教，大家一起探讨学习~

**Comment by magic0908** [comment]
OK！
其实对于titlebar的下划线，我是这样处理的，写一个layer-list的drawable，然后当做titlebar的background设置进去。以下是xml代码：
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item
        android:left="-2dp"
        android:right="-2dp"
        android:top="-2dp">
        
        <shape>
            <solid android:color="@color/white"/>
            <stroke
                android:width="0.5dp"
                android:color="@color/bottom_line"/>
        </shape>
    </item>
</layer-list>
我在titlebar的layout里直接setBackground，这样也能出现下划线。不过我感觉最终本质还是添加了一个view。另外，我们项目里的titlebar都是默认白色背景，返回（ImageView）、标题（TextView）和下划线，有些时候需要菜单。这样也是四个控件了。对于按需加载，我目前的思路是在自定义的layout里面暴露几个方法，比如我这个页面需要添加菜单，那么可以定义一个addMenuView（view），在方法里面处理显示位置的逻辑和点击事件。在activity里就直接传一个icon图标，或者一个文字，或者一个view。这样也基本能满足多数的需求了。如果你有更好的思路，也希望继续讨论~

**Comment by magic0908** [comment]
好像没法显示。。
*/*<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item
        android:left="-2dp"
        android:right="-2dp"
        android:top="-2dp">
        
        <shape>
            <solid android:color="@color/white"/>
            <stroke
                android:width="@dimen/dp_0_5"
                android:color="@color/bottom_line"/>
        </shape>
    </item>
*/*</layer-list>
